[project]
name = "pomsicle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "colorama>=0.4.6",
    "playwright>=1.55.0",
    "polars>=1.32.3",
    "requests>=2.32.5",
]
